### ISSUE TITLE
Deploy SHU on Gnosis

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/shutter-bridge#2]
### **Setup [2h]** 

The scope for testing this token path from Ethereum to Gnosis can be understood by the following steps:

- [x] Create the repository with Blockful's hardhat boilerplate.

We will be testing superficial functions mostly, there is no need for complex tests or solidity development as the OmniBridge will provide all the features to make the bridge possible.

- [x] Create our ERC20 token resembling $SHU.

### **Scripts [8h]**

We cannot rely on tests or forks for the communication test between bridges. We must use the scripts where each will do one step of the process: send from Ethereum to Gnosis and back from Gnosis to Ethereum.

- [x] Create a deploy script for the $SHU token on Sepolia
- [x] Create a script to relay tokens from the source chain to the destination chain - relayTokens(…)
- [x] Create a script to burn synthetic tokens from the destination chain to redeem the underlying on the source chain - transferAndCall(…)

The first time the token is minted on the destination chain we cannot know in advance with small effort which contract address the $SHU token will receive on the other end

### **Validation [2h]**

- [x] Create a script to fetch the token total supply and the token amount of the sender/receiver

### **Conclusion [2h]**

- [x] Documentation and optimizations of processes.

https://docs.gnosischain.com/bridges/About%20Token%20Bridges/omnibridge

**Comment by 0xneves** [comment]
When bridging tokens to the Gnosis Chain, a proxy will be created by the Validators via the mediator (omnibridge). Thus features like pausable will not be inherited from mainnet.

**Comment by 0xneves** [comment]
The synthetic $SHU token on Gnosis is located at the address:  [0x8ccd277cc638e7e17f8100ce583cbcef42007dca](https://gnosisscan.io/token/0x8ccd277cc638e7e17f8100ce583cbcef42007dca)

**Comment by 0xneves** [comment]
## How to use OmniBridge

1. Access https://bridge.gnosischain.com/
2. Connect your wallet
3. Input the Shutter Token address on the search bar
    1. https://etherscan.io/token/0xe485E2f1bab389C08721B291f6b59780feC83Fd7

![Image](https://github.com/blockful-io/shutter-bridge/assets/90667119/321fcf81-0512-4b58-b3b4-49e931f123c6)

4. Select the number of tokens you want to transfer

![Image](https://github.com/blockful-io/shutter-bridge/assets/90667119/5b927abc-db15-4e88-8ca8-e6cf844c2209)

5. Confirm the transfer. 

The token address for $SHU in Gnosis was already bridge a long time ago and will always be represented by the following address:
[0x8CCd277Cc638E7e17F8100cE583cBcEf42007Dca](https://gnosisscan.io/token/0x8ccd277cc638e7e17f8100ce583cbcef42007dca)

Currently, there is no way to register the token logo and name other than reaching out to the front-end team of the bridge dApp. Which we are already contacted and are waiting for the next steps.
