### ISSUE TITLE
SAFE on gnosis controlled by the DAO

### ISSUE THREAD

**Issue by 0xneves** [blockful-io/shutter-bridge#3]
### **Setup [2h]**

- [x] The first step is to fund the accounts on both Sepolia and Gnosis Chain.

Since UMA's oSnap is not available on Chiado (Gnosis Testnet) we must pretend that Sepolia is Ethereum, while Gnosis will be the mainnet itself since we have no other choice but to pay for gas fees during these tests.

- [x] Create the mock Spaces on Snapshot in the Sepolia network where we need to set an ENS to use.

We must create an ENS name as a requirement for Space creation on Snapshot, even on testnet.

### **Deployments [2h]**

- [x] Deploy Gnosis Safe on Gnosis chain
- [x] Deploy a mock ERC20 on Gnosis chain

We will be using the Safe to control the token assets stored in it. Executing proposals with raw bytes for functions like approve(…) and transferFrom(…).

We'll use the deploy functionalities specified in #2 to handle the mock deployment.

### **oSnap Setup [2h]**

- [x] Go to our Space's snapshot settings and add oSnap plugin. Place our treasury address and select Gnosis Chain.
- [x] To activate the oSnap, we choose to be redirected to our Treasury contract, signing the module upgrade and finishing the activation after confirming the transaction. 

Nowhere to be found the information regarding the support for Gnosis chain or not in Snapshot, and we cannot test it without a Spaces created, so it's assumed that the chain is supported for Snapshot, and it surely is for UMA's oSnap.

### **Snapshot Transactions Tests [2h]**

- [x] Now when we create proposals on Snapshot, we may opt. for the check box saying: "Yes, use oSnap for transactions”.
- [x] The last step is to configure the proposal and select a saved Safe where it will have the transaction executed.

### **Reference**

https://docs.uma.xyz/developers/osnap/osnap-deployment-tutorial
https://docs.uma.xyz/developers/osnap/snapshot-tutorial

**Comment by 0xneves** [comment]
https://testnet.snapshot.org/#/shutter-osnap.eth/proposal/0x9668f506c58425e48e4e379be0dcab7143c8c8c61f85e74c1930247883727d38

Proposal created. Although they are asking for 2 whole WETH and 3 days of challenge period...

![image](https://github.com/blockful-io/shutter-bridge/assets/90667119/a2a46c2f-4e5b-4d1d-88a4-bb0e2086ddab)

edit: trying other chains to reduce this time

**Comment by 0xneves** [comment]
Snapshot is wrongly checking MATIC Gnosis Safe, even with the oSnap activate it wrongly mistakes it for eth and consider the treasury non-existante

**Comment by 0xneves** [comment]
Manage to lower the time and costs, but is still to high for testing purposes
![image](https://github.com/blockful-io/shutter-bridge/assets/90667119/a39d367e-95a2-4460-ae57-d8368f2ba5ce)

**Comment by 0xneves** [comment]
![image](https://github.com/blockful-io/shutter-bridge/assets/90667119/66a94a00-131f-4b10-89e7-b46ab64289c2)

Sepolia requiring as low as 0.0005 for being tested but...

Something wrong with the plugin, not detecting the WETH on my wallet, nor providing any useful information. UMA team is also non-existent, discord ch is full of ghosts

**Comment by 0xneves** [comment]
Got a response from the UMA team, they are looking into the matter...

**Comment by 0xneves** [comment]
Will post the next steps soon

![Image](https://github.com/blockful-io/shutter-bridge/assets/90667119/c2da95e1-b977-4db1-abd0-e256a6df03c4)

**Comment by alextnetto** [comment]
@0xneves Please provide the next steps for production.

**Comment by Gabrielnvk** [comment]
Tutorial "How to use oSnap"

https://blockful.notion.site/How-to-use-oSnap-bc4529beda9e4b1cb3cd582555ca17fd
